services:
  data_entrypoint:
    build: ./services/data_entrypoint
    ports:
      - "3000:3000"
    environment:
      - LISTEN_TOPIC = "patient_vitals"
      - KAFKA_LISTENING = "localhost:9092"
      - KAFKA_PRODUCING = "localhost:9092"
      - CREATE_TOPIC = "updated_vitals"