// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: vitals/vitals.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vitals";

export interface GetVitalsRequest {
  patientId: string;
}

export interface GetVitalsResponse {
  patientId: string;
  heartRate: number;
  bloodPressureSystolic: number;
  bloodPressureDiastolic: number;
  temperature: number;
  oxygenSaturation: number;
  recordedAt: string;
}

export interface RecordVitalsRequest {
  patientId: string;
  heartRate: number;
  bloodPressureSystolic: number;
  bloodPressureDiastolic: number;
  temperature: number;
  oxygenSaturation: number;
}

export interface RecordVitalsResponse {
  success: boolean;
  message: string;
  recordedAt: string;
}

export const VITALS_PACKAGE_NAME = "vitals";

export interface VitalsServiceClient {
  getVitals(request: GetVitalsRequest, metadata?: Metadata): Observable<GetVitalsResponse>;

  recordVitals(request: RecordVitalsRequest, metadata?: Metadata): Observable<RecordVitalsResponse>;
}

export interface VitalsServiceController {
  getVitals(
    request: GetVitalsRequest,
    metadata?: Metadata,
  ): Promise<GetVitalsResponse> | Observable<GetVitalsResponse> | GetVitalsResponse;

  recordVitals(
    request: RecordVitalsRequest,
    metadata?: Metadata,
  ): Promise<RecordVitalsResponse> | Observable<RecordVitalsResponse> | RecordVitalsResponse;
}

export function VitalsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getVitals", "recordVitals"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VitalsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VitalsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VITALS_SERVICE_NAME = "VitalsService";
